spring.application.name=fare-payment-service
server.port=8084
spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/ridelink_fare}
ridelink.jwt.secret=${JWT_SECRET:ridelink-dev-jwt-secret-change-me-32bytes}
ridelink.jwt.expiration-ms=86400000
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
springdoc.swagger-ui.path=/swagger-ui.html
